project_name: alpacon

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.sha256"

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: alpacon-cli
    repository:
      owner: alpacanetworks
      name: alpacon-cli
    commit_author:
      name: alpacanetworksbot
      email: bot@alpacanetworks.com
    directory: Formula
    homepage: "https://github.com/alpacanetworks/alpacon-cli"
    description: "CLI for Alpaca Infra Platform"

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - alpacon
    image_templates:
      - "alpacanetworks/alpacon-cli:latest"
      - "alpacanetworks/alpacon-cli:{{ .Tag }}"
    dockerfile: Dockerfile

nfpms:
  - maintainer: Younghwan Kim <yh.kim@alpacanetworks.com>
    description: Alpacon-CLI
    homepage: https://github.com/alpacanetworks/alpacon-cli
    license: MIT
    vendor: Alpaca Networks
    formats:
      - deb
      - rpm

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"