# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AlpaconCli < Formula
  desc "CLI for Alpaca Infra Platform"
  homepage "https://github.com/alpacanetworks/alpacon-cli"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/alpacanetworks/alpacon-cli/releases/download/0.2.0/alpacon-0.2.0-darwin-amd64.tar.gz"
      sha256 "2eb79c0cfca95927ec18aec7926568424fc6dea8586826ffadcad0abfdfec331"

      def install
        bin.install "alpacon"
      end
    end
    on_arm do
      url "https://github.com/alpacanetworks/alpacon-cli/releases/download/0.2.0/alpacon-0.2.0-darwin-arm64.tar.gz"
      sha256 "e4472934a55488e787a67ae88107a529477d9c9be4f9072633e05bbbb66ce9a1"

      def install
        bin.install "alpacon"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alpacanetworks/alpacon-cli/releases/download/0.2.0/alpacon-0.2.0-linux-amd64.tar.gz"
        sha256 "9b4638fa46ac7c7c105ab4ea50e080e7fe29b8bc672a673c97b5eec55343e869"

        def install
          bin.install "alpacon"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/alpacanetworks/alpacon-cli/releases/download/0.2.0/alpacon-0.2.0-linux-arm.tar.gz"
        sha256 "e11fcc2009f83efc4aa3f3e84e1e860f5456e2a9b062a07772091d547ce57e8c"

        def install
          bin.install "alpacon"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alpacanetworks/alpacon-cli/releases/download/0.2.0/alpacon-0.2.0-linux-arm64.tar.gz"
        sha256 "eed2ee7bee4ad526eb3138a6bf90504257c9f87759b769bfa9bbcb11d87e3ce5"

        def install
          bin.install "alpacon"
        end
      end
    end
  end
end
