name: Build and Test
on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"

  pull_request:
    types: [opened, ready_for_review]

  workflow_call:
    secrets: inherit

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: go build -v .

      - name: Run Tests
        run: go test -v ./...
