name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

# permissions:
  # contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: dist/*


  packagecloud-deploy:
    needs: goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages

      - name: Upload AMD64 DEB to PackageCloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: dist/*.amd64.deb
          PACKAGECLOUD-USERNAME: alpacanetworks
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: any/any
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - name: Upload AMD64 RPM to PackageCloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: dist/*.amd64.rpm
          PACKAGECLOUD-USERNAME: alpacanetworks
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: any/any
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}