name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

# permissions:
  # contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}

      - name: Upload AMD64 DEB to PackageCloud for Ubuntu 18.04
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: dist/*.amd64.deb
          PACKAGECLOUD-USERNAME: alpacanetworks
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: ubuntu/bionic
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - name: Upload AMD64 DEB to PackageCloud for Ubuntu 20.04
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: dist/*.amd64.deb
          PACKAGECLOUD-USERNAME: alpacanetworks
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: ubuntu/focal
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }


      - name: Upload AMD64 DEB to PackageCloud for Ubuntu 22.04
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: dist/*.amd64.deb
          PACKAGECLOUD-USERNAME: alpacanetworks
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: ubuntu/jammy
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }

      - name: Upload AMD64 RPM to PackageCloud for CentOS7
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: dist/*.amd64.rpm
          PACKAGECLOUD-USERNAME: alpacanetworks
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: el/7
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - name: Upload AMD64 RPM to PackageCloud for CentOS8
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: dist/*.amd64.rpm
          PACKAGECLOUD-USERNAME: alpacanetworks
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: el/8
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}


      - name: Upload AMD64 RPM to PackageCloud for CentOS9
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: dist/*.amd64.rpm
          PACKAGECLOUD-USERNAME: alpacanetworks
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: el/9
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}