name: Release

on:
  push:
    tags:
      - "*"


jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  goreleaser:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload AMD64 DEB artifacts
        uses: actions/upload-artifact@v3
        with:
          name: alpacon_${{ github.ref_name }}_linux_amd64.deb
          path: dist/alpacon_${{ github.ref_name }}_linux_amd64.deb

      - name: Upload AMD64 RPM artifacts
        uses: actions/upload-artifact@v3
        with:
          name: alpacon_${{ github.ref_name }}_linux_amd64.rpm
          path: dist/alpacon_${{ github.ref_name }}_linux_amd64.rpm

  packagecloud-deploy:
    needs: [goreleaser]
    runs-on: ubuntu-latest
    steps:
      - name: Download AMD64 DEB Artifacts
        uses: actions/download-artifact@v3
        with:
          name: alpacon_${{ github.ref_name }}_linux_amd64.deb

      - name: Download AMD64 RPM Artifacts
        uses: actions/download-artifact@v3
        with:
          name: alpacon_${{ github.ref_name }}_linux_amd64.rpm

      - run: ls

      - name: Upload AMD64 DEB to PackageCloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: alpacon_${{ github.ref_name }}_linux_amd64.deb
          PACKAGECLOUD-USERNAME: alpacanetworks
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: any/any
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - name: Upload AMD64 RPM to PackageCloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: alpacon_${{ github.ref_name }}_linux_amd64.rpm
          PACKAGECLOUD-USERNAME: alpacanetworks
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: rpm_any/rpm_any
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}